# Generated by Django 4.2.9 on 2024-03-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tab_aux",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=20)),
                ("libelle", models.CharField(max_length=255)),
            ],
        ),
    ]
