# Generated by Django 4.2.9 on 2024-03-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_tab_banque_tab_com"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tab_aux",
            table="Tab_aux",
        ),
        migrations.AlterModelTable(
            name="tab_banque",
            table="Tab_banque",
        ),
        migrations.AlterModelTable(
            name="tab_com",
            table="Tab_com",
        ),
    ]
