# Generated by Django 4.2.9 on 2024-03-31 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_tab_aux_table_alter_tab_banque_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab_com",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
