# Generated by Django 4.2.9 on 2024-04-01 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_tab_aux_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tab_coffre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=20)),
                ("libelle", models.CharField(max_length=255)),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "Tab_coffre",
            },
        ),
        migrations.AddField(
            model_name="tab_banque",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
